table 'Fact Procurement'

	column Spend
		dataType: double
		summarizeBy: sum
		sourceColumn: Spend

	column Vendor
		dataType: string
		summarizeBy: none
		sourceColumn: Vendor

	column Currency
		dataType: string
		summarizeBy: none
		sourceColumn: Currency

	column POID
		dataType: string
		summarizeBy: none
		sourceColumn: POID

	measure 'Total Spend' = SUM('Fact Procurement'[Spend])
		formatString: "#,0"

	measure 'Avg Spend' = AVERAGE('Fact Procurement'[Spend])
		formatString: "#,0.00"

	measure 'Purchase Price Variance' =
			VAR CurrentPrice = SUM('Fact Procurement'[Spend])
			VAR StandardPrice = SUM(Dim_Material[StandardCost])
			RETURN
			CurrentPrice - StandardPrice
		formatString: "#,0"

	partition 'Fact Procurement' = m
		mode: import
		source = let Source = 1 in Source
